functions:build:
  extends: .serverless:build:functions
  environment:
    name: production
    action: prepare
  needs: []
  dependencies: []

functions:deploy:
  extends: .serverless:deploy:functions
  environment:
    name: production
    action: start
  dependencies: []
  needs:
    - "functions:build"

include:
  - template: Serverless.gitlab-ci.yml