variables:
  AUTO_CNB_RUN_IMAGE: harbor.dcas.dev/docker.io/paketobuildpacks/run:tiny-cnb

stages:
  - build
  - predeploy
  - deploy

build:
  stage: build
  extends: .auto-build
  dependencies: []
  needs: []
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS != null && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_BRANCH == null && $CI_OPEN_MERGE_REQUESTS == null'
      when: never
    - if: '$BUILD_DISABLED != null'
      when: never
    - when: on_success

container-scanning:
  dependencies: []
  needs:
    - build


deploy:
  dependencies: []
  stage: deploy
  needs:
    - build
    - container-scanning
  image: harbor.dcas.dev/registry.gitlab.com/autokubeops/cuttle:v0.1
  environment:
    name: production
    action: start
  script:
    - cuttle regcred
    - cuttle function deploy
  resource_group: production
  rules:
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$DEPLOY_DISABLED || $CI_DEPLOY_FREEZE'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

include:
  - remote: "https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/defend/ContainerScanning.gitlab-ci.yml"
  - remote: "https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/build/CNB.gitlab-ci.yml"
